### PR TITLE
OS X compatibility

### PR DESCRIPTION
**Pull request by evenh**
Modified to run under OS X. Only tested with Yosemite, so I don't know if the bash script will break compatibility with Linux or other platforms.

### CODE REVIEW

**Comment by jaroslavtyc** [comment]
Thank you Even for your participation!

I could not merge your suggested changes into master because of incompatibility with Linux bash syntax, but i [copied your branch as standalone one](https://github.com/jaroslavtyc/git-commit-autoprefix/tree/osx-compatible).

Please notice my mistake with prepare-commit-message hook. The use of [commit-message](https://github.com/jaroslavtyc/git-commit-autoprefix/commit/b512b9c7ba2324ee13b4a6ca59b134f318d1fbdc) hook is more comfortable.

Keep up the good work!

**Comment by evenh** [comment]
No problem! Thank you for writing this little hook, it solved my problem today :tophat:. What are the benefits of doing this in the `commit-message` hook rather than in the `prepare-commit-message` hook?

**Comment by jaroslavtyc** [comment]
It's all about laziness (read "automation".-])
`prepare-commit-message` prepends the issue key, but if you will commit from command line interactively, without inline commit message

```
git commit
```

the issue key is already there - in the text editor, forcing you to click _behind_ the text to write the message

```
{text cursor is here}FOO-123
```

That will not happened with `commit-message`.
The issue key will be appended always _after_ committing the message.
No needs to care about anything.

**Comment by evenh** [comment]
Thanks for clarifying that :+1: I will implement it in the `commit-message` in my fork to ensure maximum laziness throughout my projects :)

**Pull request closed without merging**
